#!/bin/sh

IF=$BLOCK_INSTANCE
USE_PERCENT=0

[[ ! -d /sys/class/net/${IF} ]] && exit

[[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]] && exit

ssid=$(iwgetid -r)
dbm=$(iw dev "$IF" link | grep 'dBm$' | grep -Eoe '-[0-9]{2}')

[[ -n "$dbm" ]] || exit 1

if [[ $USE_PERCENT -eq 0 ]]; then
    echo "($ssid $dbm dBm)"
    echo "($ssid $dbm)"
else
    if [[ "$dbm" -le -100 ]]; then
        quality=0
    elif [[ $dbm -ge -50 ]]; then
        quality=100
    else
        quality=$((2 * (dbm + 100)))
    fi
    echo "$quality%"
    echo "$quality%"
fi

if [[ $dbm -ge -55 ]]; then
	echo "#00FF00"
elif [[ $dbm -ge -60 ]]; then
	echo "#CCFF00"
elif [[ $dbm -ge -70 ]]; then
	echo "#FFFF00"
elif [[ $dbm -ge -80 ]]; then
	echo "#FFAA00"
else
	echo "#FF0000"
fi
