#!/bin/sh

COLOR=""

if [ -d /proc/sys/net/ipv4/conf/tun0 ]; then
   VPN=$(ps -C openvpn -o cmd= | sed 's=.*/==;s=\.[^.]*$==')
   COLOR="#00ff00"

   if [ -z "$VPN" ]; then
      VPN="(broken)"
      COLOR="#ff0000"
   fi
else
  VPN="(down)"
fi

echo $VPN
echo $VPN
[ -z $COLOR ] || echo $COLOR